# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Get project version
      uses: lukka/get-cmake@latest
    - name: "Package build in tarball"
      run: tar -czvf ${{github.workspace}}/build/stringc-x86_64.tar.gz ${{github.workspace}}/build/libstring.a ${{github.workspace}}/include
    - name: Upload built release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: ${{github.workspace}}/build/*.tar.gz
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: $CMAKE_PROJECT_VERSION
